### ISSUE TITLE
Add images for README.md

### ISSUE THREAD

**Issue by axelvaindal** [axelvaindal/HermesProject#44]
![core](https://cloud.githubusercontent.com/assets/11026659/16233779/c76849d8-37cf-11e6-98d1-e3766d274eb1.png)
![diagramme des composants](https://cloud.githubusercontent.com/assets/11026659/16233778/c7598204-37cf-11e6-8e46-18837fe142e8.png)
![sdwriter](https://cloud.githubusercontent.com/assets/11026659/16233780/c76f9ac6-37cf-11e6-9503-97d1fa5c912d.png)
![sensors](https://cloud.githubusercontent.com/assets/11026659/16233777/c7594578-37cf-11e6-876c-b93a359413e6.png)
![globalcase](https://cloud.githubusercontent.com/assets/11026659/16233849/fb8ba6d8-37cf-11e6-81e6-b4ead74d2846.jpg)
![hermesglobal](https://cloud.githubusercontent.com/assets/11026659/16233847/fb892174-37cf-11e6-8f50-d446b903575e.jpg)
![hermesglobalschema](https://cloud.githubusercontent.com/assets/11026659/16233851/fb8df924-37cf-11e6-9abc-da73f654e6af.jpg)
![arduinocasebottom](https://cloud.githubusercontent.com/assets/11026659/16233848/fb8b4cd8-37cf-11e6-9d6f-8658492794e0.jpg)
![arduinocasetop](https://cloud.githubusercontent.com/assets/11026659/16233852/fba02162-37cf-11e6-8098-4db12e32b809.jpg)
![circuitcase](https://cloud.githubusercontent.com/assets/11026659/16233850/fb8bd90a-37cf-11e6-8fd8-426b371c0d3c.jpg)
![circuitcasefull](https://cloud.githubusercontent.com/assets/11026659/16233853/fbb46d02-37cf-11e6-9bb5-ffac6860c8ea.jpg)
![13499555_10206779663272913_209035400_o](https://cloud.githubusercontent.com/assets/11026659/16234120/cedd3722-37d0-11e6-8bb0-04d2fe67dd39.png)

**Comment by axelvaindal** [comment]
![casing](https://cloud.githubusercontent.com/assets/11026659/16308198/54ea414a-3964-11e6-9d4b-2ba3543733ee.jpg)
![projet_hermes](https://cloud.githubusercontent.com/assets/11026659/16308199/54eb1a66-3964-11e6-9a87-52cf21e407a8.png)

**Comment by axelvaindal** [comment]
![projet_hermes](https://cloud.githubusercontent.com/assets/11026659/16308423/316115ea-3965-11e6-9005-b7155d6840fd.png)

**Comment by axelvaindal** [comment]
![chronologie](https://cloud.githubusercontent.com/assets/11026659/16318978/9802e5cc-3991-11e6-81d7-3761500a6dd6.png)

**Comment by axelvaindal** [comment]
![mind map](https://cloud.githubusercontent.com/assets/11026659/16319468/c1ce39f4-3993-11e6-8445-64abb2495414.png)

**Comment by axelvaindal** [comment]
![image](https://cloud.githubusercontent.com/assets/11026659/16321556/d1ed9f96-399d-11e6-9d2b-f47db18e98ae.png)

**Comment by axelvaindal** [comment]
![image](https://cloud.githubusercontent.com/assets/11026659/16322113/3b06c400-39a1-11e6-8d1d-7c6c6f6a2313.png)

**Comment by aunimhsn** [comment]
![business_approach](https://cloud.githubusercontent.com/assets/9677426/16322531/fca4a832-39a3-11e6-9241-30044945a71f.png)

**Comment by axelvaindal** [comment]
![image](https://cloud.githubusercontent.com/assets/11026659/16323140/ca06e606-39a8-11e6-9b00-c480129da958.png)

**Comment by axelvaindal** [comment]
![image](https://cloud.githubusercontent.com/assets/11026659/16323573/11e07250-39ac-11e6-85c0-06c3d2e385c8.png)
